### ISSUE TITLE
Request for Open Sourcing Processed Data

### ISSUE THREAD

**Issue by meta-tabchen** [umass-ml4ed/dialogue-kt#1]
Great work on the project! I’m curious if you plan to open source the processed data? It would be incredibly helpful for the community to build upon.

**Comment by alexscarlatos** [comment]
Hi Jiahao,

Thanks so much for your interest in our work and for the suggestion! I agree this would be useful to folks, so I've released the processed data under `data/annotated` and updated the README accordingly.

Best,
Alex
